services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      DATABASE: /app/data/memo_service.db
    restart: unless-stopped

  caddy:
      image: caddy:alpine
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
      depends_on:
        - app
      restart: unless-stopped

  volumes:
    caddy_data: